/**
 * handlebars-helper-bundles
 * Handlebars helper that process bundles generated by metalsmith-bundles.
 *
 * @author Antonio Hernandez <ahdiaz@gmail.com>
 * @license MIT
 *
 * @see https://github.com/ahdiaz/metalsmith-bundles
 */

function plugin(handlebars, options) {

    handlebars.registerHelper('bundles', function (section, options) {
        try {
            var data = options.data.root.bundlesData[section];
        } catch (e) {
            var data = '';
        }
        var ret = new Handlebars.SafeString(data);
        return ret;
    });
}

module.exports = plugin;
